config/routes.rb
Rails.application.routes.draw do
  root 'index#home'
  devise_for :users



  resources :posts do
    resources :comments
    member do
      post :likes
      post :unlikes
    end
  end

  resources :users, except: [:destroy, :create] do
    # resources :avatars
    member do
      post :follow
      post :unfollow
      get :followers
      get :followees
      get :news
      post :likes
      post :unlikes
      get :search
    end
  end

  get 'mailbox' => 'mailbox#index', as: :mailbox_index
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  # resources :mailbox, only: [:inbox, :sent, :trash]

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get 'search', to: 'search#search'
  # resources :profiles do
  #   member do
  #     post :follow
  #     post :unfollow
  #   end
  # end

  # resources :dialogs do
  #   resources :messages
  # end

  # resources :conversations, only: [:index, :show, :destroy] do
  #   collection do
  #     delete :empty_trash
  #   end
  # member do
  #   post :reply
  #   post :mark_as_read
  # end
  # end
  # resources :messages, only: [:new, :create] do
  #   member do
  #     post :restore
  #   end
  # end
  # post 'users#followers'
 #root 'posts#profile'
  # root 'user', to: 'users#show'

  #root 'profiles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'users/profile', as: 'user_root'
  # get 'users/show', as: 'users'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  paginates_per 3

  acts_as_likeable
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
    #has_many :likes, #dependent: :destroy

    acts_as_likeable
    # acts_as_followable
end

app/models/user.rb
require 'elasticsearch/model'
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mapping do
    indexes :email, type: 'text'
    indexes :first_name, type: 'string', :index_analyzer => 'simple', :search_analyzer => 'simple'
    indexes :second_name, type: 'string', :index_analyzer => 'simple', :search_analyzer => 'simple'
  end
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable


  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  has_many :comments
  #validates :name, presence: true


  acts_as_followable
  acts_as_follower
  acts_as_liker

  acts_as_messageable



  def mailboxer_name
    self.first_name
  end

  def mailboxer_email(object)
    self.email
  end

  # def full_name
  #   "#{first_name} #{second_name}"
  # end

  def as_indexed_json (options={})
    self.as_json({
      only: [:id, :first_name, :second_name],
      include: [:posts],
      # methods: [:full_name]
     })
  end

  def self.search(query)
    __elasticsearch__.search(
        {
            query: {
                multi_match: {
                    query: query,
                    fields: ['first_name', 'second_name']
                }
            },
            highlight: {
              pre_tags: ['<em>'],
              post_tags: ['</em>'],
              fields: {
                  first_name: {},
                  second_name: {}
            }
        }
      }
    )
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :first_name, analyzer: 'english'
      indexes :second_name, analyzer: 'english'
    end
  end

  #attr_accessible :image, :image_cash, :remote_image
  #has_attached_file :avatar, :styles => { :thumb => "75x75>", :small => "150x150>" }
end
# User.import
# @user = User.search('fion').records

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def home
    if current_user
      redirect_to current_user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow, :followers, :followees]
  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def update
    respond_to do |format|
      if @user.update(users_params)
        format.html { redirect_to @user, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def follow
    current_user.follow!(@user) # => This assumes you have a variable current_user who is authenticated
    render :follow_button
  end

  def unfollow
    current_user.unfollow!(@user)
    render :follow_button
  end

  def followers
    @followers = @user.followers(User)
    @users = User.all
  end

  def followees
    @followees = @user.followees(User)
    @users = User.all
  end

  def news
  end

  def search
    if params[:q].nil?
      @users = []
    else
      @users = User.search params[:q]
    end
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:id,  :first_name, :second_name, :avatar)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_header(text)
    content_for(:page_header) { text.to_s }
  end

  def flash_class(level)
    case level
      when 'notice' then "alert alert-dismissable alert-info"
      when 'success' then "alert alert-dismissable alert-success"
      when 'error', 'alert' then "alert alert-dismissable alert-danger"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    if resource.errors.full_messages.any?
      flash.now[:error] = resource.errors.full_messages.join(', ')
    end
    return ''
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  # def unread_messages_count
  #   # how to get the number of unread messages for the current user
  #   # using mailboxer
  #   mailbox.inbox(:unread => true).count(:id, :distinct => true)
  # end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name} #{user.second_name}</option>"
    end
    s.html_safe
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.haml
- if current_user.follows?(user)
  = link_to('Unfollow', unfollow_user_path(user), method: :post, remote: true)
- else
  = link_to('Follow', follow_user_path(user), method: :post, remote: true)

app/views/users/_form.html.haml
-#%h3.text-center.login-title Users#profile
-#%p.text-center.notice= notice
-#%p.text-center.alert= alert

%body.bg
  .container
    .row
      .main-login.main-center
        = form_for @user, html: { multipart: true } do |f|
          - if @user.errors.any?
            #error_explanation
              %h2= "#{pluralize(@user.errors.count, "error")} prohibited this profile from being saved:"
              %ul
                - @user.errors.full_messages.each do |msg|
                  %li= msg
          .field.text-center
            = f.label :first_name
            = f.text_field :first_name
          .field.text-center
            = f.label :second_name
            = f.text_field :second_name

          .field.text-center.act
            = f.label :avatar
            = f.file_field :avatar

            .actions.text-center.act
              = f.submit 'Save'

app/views/users/_post.html.haml
.row
  .news-name{style: 'display: inline-block'}
    .img-img2= image_tag("#{post.user.avatar.url}", class: 'img-img2')
    %a.account-name= link_to("#{post.user.first_name} #{post.user.second_name}", user_path(post.user))

  %a.text-center.thumbnail{href: post_path(post.id)}
    %p= image_tag post.image

  .card-block.news
    .like_button{class: "post-like-#{post.id}"}
      - if current_user.likes?(post)
        = link_to unlikes_post_path(post), method: :post, remote: true do
          %i.fa.fa-heart
      - else
        = link_to likes_post_path(post), method: :post, remote: true do
          %i.fa.fa-heart-o
      = post.likers(User).count

  %p.card-text.news= post.description
  %p.timestamp.news= post.created_at.strftime("%-d %B %Y, %H:%M:%S")
  -#= render 'users/news', user: current_user

app/views/users/_posts.html.haml
- posts.each do |post|
  = render 'users/post', post: post

app/views/users/edit.html.haml
%h1.text-center Editing profile
.text-center
  = render 'form'

  -#= link_to 'Show', @user
  -#\|
  -#= link_to 'Back', user_path

app/views/users/follow_button.js.haml
$(".follow-unfollow").html("#{escape_javascript render(partial: 'users/follow_button', locals: { user: @user }) }")

app/views/users/followees.html.haml
.container
  - if current_user != @user
    %h3.text-center Following from #{@user.first_name} #{@user.second_name}
  - else
    %h3.text-center Your following
  .container
    - if @user.followees(User).count == 0
      %h3 подписок нет
    - else
      %tbody
        - @user.followees(User).each do |user|
          .row.header-menu
            .col-xs-2
              .img-img= image_tag("#{user.avatar.url}", class: 'img-img')
            .col-xs-9.panel-name
              .panel.panel-follow
                - if user.first_name == nil
                  %h2= link_to('NO NAME', user_path(user))
                - else
                  %h2= link_to("#{user.first_name} #{user.second_name}", user_path(user))
                -#- if current_user == user
                -#  %span{style: 'padding-left: 50px; padding-bottom: 15px display: inline-block'}
                -#  = link_to 'Редактировать профиль', edit_user_path(user), class: 'btn btn-secondary'
                -#- else
                -#  %span.opacity чужой аккаунт
                -#- if current_user.id == user.id
                -#  %span{style: 'padding-left: 50px; padding-bottom: 15px'}
                -#  = link_to 'New photo', new_post_path, class: 'btn btn-secondary'
              .panel2{style: 'display: inline-block'}
                %p.h4{style: 'display: inline-block'}
                  Photos
                  %span #{user.posts.count}
                %p.h4{style: 'display: inline-block'}
                  = link_to("Followers #{user.followers(User).count}", followers_user_path(user))
                %p.h4{style: 'display: inline-block'}
                  = link_to("Following #{user.followees(User).count}", followees_user_path(user))
                  %span
                -#.col-xs-5
                -#  - if current_user != user
                -#    .follow-unfollow
                -#      - if current_user.follows?(user)
                -#        = link_to('Unfollow', unfollow_user_path(user), method: :post, remote: true)
                -#      - else
                -#        = link_to('Follow', follow_user_path(user), method: :post, remote: true)

app/views/users/followers.html.haml
- if current_user != @user
  %h3.text-center Followers from #{@user.first_name} #{@user.second_name}
-else
  %h3.text-center Your followers
.container
  - if @user.followers(User).count == 0
    %h3 Фолловеров нет
  - else
    - @user.followers(User).each do |user|
      .row.header-menu
        .col-xs-2
          .img-img= image_tag("#{user.avatar.url}", class: 'img-img')
        .col-xs-9.panel-name
          .panel.panel-follow
            - if user.first_name == nil
              %h2= link_to('NO NAME', user_path(user))
            - else
              %h2= link_to("#{user.first_name} #{user.second_name}", user_path(user))
            -#- if current_user == user
            -#  %span{style: 'padding-left: 50px; padding-bottom: 15px display: inline-block'}
            -#  = link_to 'Редактировать профиль', edit_user_path(user), class: 'btn btn-secondary'
            -#- else
            -#  %span.opacity чужой аккаунт
            -#- if current_user.id == user.id
            -#  %span{style: 'padding-left: 50px; padding-bottom: 15px'}
            -#  = link_to 'New photo', new_post_path, class: 'btn btn-secondary'
          .panel2{style: 'display: inline-block'}
            %p.h4{style: 'display: inline-block'}
              Photos
              %span #{user.posts.count}
            %p.h4{style: 'display: inline-block'}
              = link_to("Followers #{user.followers(User).count}", followers_user_path(user))
            %p.h4{style: 'display: inline-block'}
              = link_to("Following #{user.followees(User).count}", followees_user_path(user))
              %span
            -#.col-xs-5
            -#  - if current_user != user
            -#    .follow-unfollow
            -#      - if current_user.follows?(user)
            -#        = link_to('Unfollow', unfollow_user_path(user), method: :post, remote: true)
            -#      - else
            -#        = link_to('Follow', follow_user_path(user), method: :post, remote: true)

app/views/users/new.html.haml
- if !@user.error.empty?
  .alter.alter-error
    %ul
      - @user.errors.full_messages.each do |msg|
        %li msg
.well
  = form_for @user, html: { multipart: true } do |f|
    = f.label :title
    = f.text_field :title
    = f.label :image
    = f.file_field :image
    = f.submit "Save", class: "btn btn-primary"

app/views/users/news.html.haml
%link{:href => "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", :rel => "stylesheet"}
-# так надо
.container
  %h3.text-center NEWS
  .card.card-news{style: 'width: 70rem'}
    - if current_user.followees(User).count == 0
      %h3.text-center Новостей нет
    - else
      .card
      - Post.where(user_id: current_user.followees(User).pluck(:id)).limit(5).each do |post|
        .row
          .news-name{style: 'display: inline-block'}
            .img-img2= image_tag("#{post.user.avatar.url}", class: 'img-img2')
            %a.account-name= link_to("#{post.user.first_name} #{post.user.second_name}", user_path(post.user))

        %a.text-center.thumbnail{href: post_path(post.id)}
          %p= image_tag post.image

        .card-block.news
          .like_button{class: "post-like-#{post.id}"}
            - if current_user.likes?(post)
              = link_to unlikes_post_path(post), method: :post, remote: true do
                %i.fa.fa-heart
            - else
              = link_to likes_post_path(post), method: :post, remote: true do
                %i.fa.fa-heart-o
            = post.likers(User).count

        %p.card-text.news= post.description
        %p.timestamp.news= post.created_at.strftime("%-d %B %Y, %H:%M:%S")

      -#.news-new{class: "news-new-#{post.id}"}
      -#  = link_to 'Load more', news_user_path(post, page: 2), remote: true

app/views/users/profile.html.haml
%h3.text-center.login-title Users#profile
%p.text-center.notice= notice
%p.text-center.alert= alert

- if !flash[:notice].blank?
  .alert.alert-info
    = flash[:notice]

.row
  .col-sm-6.col-md-4
  - if user_signed_in?
    %span
      Здравствуйте, #{current_user.email}
      - if current_user.confirmed?
        %span (подтвержден)
      - else
        %span (не подтвержден)
    = link_to 'Выйти', destroy_user_session_path, :method => :delete
    %h2.text_center
    = link_to 'Listing posts', posts_path
    %head
  - else
    = link_to 'Войти', new_user_session_path
    или #{link_to 'Зарегистрироваться', new_user_registration_path}
%head
  %header.clearfix.feed-header{"data-role" => "banner"}
    - @posts.each_with_index do |post, index|
      .compWrapper
        .compInnerWrapper
          #cycler1.compContainer
            .compPhoto{class: "compPhoto#{index+1}"}
              %a{:href => post.image}
                .Image.iWithTransition
                  %img.img-responsive{:src => post.image}/
                  %b.compPhotoShadow

app/views/users/search.html.haml
%h1 Users Search
= form_for search_user_path, method: :get do |f|
  %p
    = f.label "Search for"
    = text_field_tag :q, params[:q]
    = submit_tag "Go", name: nil
%ul
  - @users.each do |user|
    %li
      %h3
        = link_to user.try(:highlight).try(:second_name) ? user.highlight.second_name[0].html_safe : user.second_name, |
          controller: "users",                                                                             |
          action: "show",                                                                                     |
          id: user._id
      - if user.try(:highlight).try(:second_name)
        - user.highlight.second_name.each do |snippet|
          %p
            = snippet.html_safe
            \...

app/views/users/show.html.haml
%link{:href => "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", :rel => "stylesheet"}
-# так надо
.container
  .form-group
    .row.header-menu
      .col-xs-2
        .img-img= image_tag("#{@user.avatar.url}", class: 'img-img')
        -#%img.img-img{ src: "#{@user.avatar.url}"}/

      .col-xs-9.panel-name
        .panel
          %p.h2{style: 'display: inline-block'} #{@user.first_name} #{@user.second_name}
          - if current_user == @user
            %span{style: 'padding-left: 50px; padding-bottom: 15px display: inline-block'}
            = link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-secondary'
          -#- else
          -#  %span.opacity чужой аккаунт

          - if current_user.id == @user.id
            %span{style: 'padding-left: 50px; padding-bottom: 15px'}
            = link_to 'New photo', new_post_path, class: 'btn btn-secondary'

        .panel{style: 'display: inline-block'}
          -#.col-xs-12{style: 'display: inline-block'}

          %p.h4{style: 'display: inline-block'}
            Photos
            %span #{@user.posts.count}

          %p.h4{style: 'display: inline-block'}
            = link_to("Followers #{@user.followers(User).count}", followers_user_path(@user))

          %p.h4{style: 'display: inline-block'}
            = link_to("Following #{@user.followees(User).count}", followees_user_path(@user))
            %span

          .col-xs-5
            - if current_user != @user
              .follow-unfollow
                - if current_user.follows?(@user)
                  = link_to('Unfollow', unfollow_user_path(@user), method: :post, remote: true)
                - else
                  = link_to('Follow', follow_user_path(@user), method: :post, remote: true)


    .feed-photos
      .row-fluid
        .span12
          - @user.posts.each_slice(3) do |posts|
            %ul.thumbnails.user-media-thumbnails
              - if posts.count == 0
                %h2.text-center Постов нет
              - else
                - posts.each do |post|
                  %li.span4
                    %a.thumbnail.img-profile{href: post_path(post.id)}
                      %img.img-profile1{src: post.image}/
                      .meta
                        %i.icon-heart
                        #{Like.where(likeable_id: post.id).count}
                        %i.icon-comment
                        #{Comment.where(post_id: post.id).count}