config/routes.rb
Rails.application.routes.draw do
  root 'index#home'
  devise_for :users



  resources :posts do
    resources :comments
    member do
      post :likes
      post :unlikes
    end
  end

  resources :users, except: [:destroy, :create] do
    # resources :avatars
    member do
      post :follow
      post :unfollow
      get :followers
      get :followees
      get :news
      post :likes
      post :unlikes
      get :search
    end
  end

  get 'mailbox' => 'mailbox#index', as: :mailbox_index
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  # resources :mailbox, only: [:inbox, :sent, :trash]

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get 'search', to: 'search#search'
  # resources :profiles do
  #   member do
  #     post :follow
  #     post :unfollow
  #   end
  # end

  # resources :dialogs do
  #   resources :messages
  # end

  # resources :conversations, only: [:index, :show, :destroy] do
  #   collection do
  #     delete :empty_trash
  #   end
  # member do
  #   post :reply
  #   post :mark_as_read
  # end
  # end
  # resources :messages, only: [:new, :create] do
  #   member do
  #     post :restore
  #   end
  # end
  # post 'users#followers'
 #root 'posts#profile'
  # root 'user', to: 'users#show'

  #root 'profiles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'users/profile', as: 'user_root'
  # get 'users/show', as: 'users'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  paginates_per 3

  acts_as_likeable
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
    #has_many :likes, #dependent: :destroy

    acts_as_likeable
    # acts_as_followable
end

app/models/user.rb
require 'elasticsearch/model'
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mapping do
    indexes :email, type: 'text'
    indexes :first_name, type: 'string', :index_analyzer => 'simple', :search_analyzer => 'simple'
    indexes :second_name, type: 'string', :index_analyzer => 'simple', :search_analyzer => 'simple'
  end
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable


  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  has_many :comments
  #validates :name, presence: true


  acts_as_followable
  acts_as_follower
  acts_as_liker

  acts_as_messageable



  def mailboxer_name
    self.first_name
  end

  def mailboxer_email(object)
    self.email
  end

  # def full_name
  #   "#{first_name} #{second_name}"
  # end

  def as_indexed_json (options={})
    self.as_json({
      only: [:id, :first_name, :second_name],
      include: [:posts],
      # methods: [:full_name]
     })
  end

  def self.search(query)
    __elasticsearch__.search(
        {
            query: {
                multi_match: {
                    query: query,
                    fields: ['first_name', 'second_name']
                }
            },
            highlight: {
              pre_tags: ['<em>'],
              post_tags: ['</em>'],
              fields: {
                  first_name: {},
                  second_name: {}
            }
        }
      }
    )
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :first_name, analyzer: 'english'
      indexes :second_name, analyzer: 'english'
    end
  end

  #attr_accessible :image, :image_cash, :remote_image
  #has_attached_file :avatar, :styles => { :thumb => "75x75>", :small => "150x150>" }
end
# User.import
# @user = User.search('fion').records

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_header(text)
    content_for(:page_header) { text.to_s }
  end

  def flash_class(level)
    case level
      when 'notice' then "alert alert-dismissable alert-info"
      when 'success' then "alert alert-dismissable alert-success"
      when 'error', 'alert' then "alert alert-dismissable alert-danger"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    if resource.errors.full_messages.any?
      flash.now[:error] = resource.errors.full_messages.join(', ')
    end
    return ''
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  # def unread_messages_count
  #   # how to get the number of unread messages for the current user
  #   # using mailboxer
  #   mailbox.inbox(:unread => true).count(:id, :distinct => true)
  # end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name} #{user.second_name}</option>"
    end
    s.html_safe
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mailbox/_folder_view.html.haml
.container
  .row
    .spacer
    .col-md-12
      = link_to 'New message', new_conversation_path, class: 'btn btn-success'
      .spacer
    .col-md-4
      .panel.panel-default
        .panel-body
          = render 'mailbox/folders'
    -#.col-md-8
    -#  .panel.panel-default
    -#    .panel-body
    .col-md-8
      - if is_conversation
        = render 'conversations/form'
      - else
        = render partial: 'conversations/conversation', collection: messages

app/views/mailbox/_folders.html.haml
%ul.nav.nav-pills.nav-stacked{style: 'display: inline-block'}
  %li.nav-item{class: "#{active_page(:inbox)}"}= link_to 'Inbox', mailbox_inbox_path

  %li{class: "#{active_page(:sent)}"}= link_to 'Outbox', mailbox_sent_path

  %li{class: "#{active_page(:trash)}"}= link_to 'Trash', mailbox_trash_path

app/views/mailbox/inbox.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox }

app/views/mailbox/index.html.haml
.media
  .media-left
    %a
      %img.media-object{src: "http://placehold.it/64x64"}/
  .media-body
    %h4.media-heading
      = conversation.originator.first_name
      %br/
      %small
        %b Subject:
        = conversation.subject
      %br/
      %small
        %b Date:
        = conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
    = truncate conversation.messages.last.body, length: 145
    = link_to "View", conversation_path(conversation)

app/views/mailbox/sent.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent }

app/views/mailbox/trash.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash }