config/routes.rb
Rails.application.routes.draw do
  root 'index#home'
  devise_for :users



  resources :posts do
    resources :comments
    member do
      post :likes
      post :unlikes
    end
  end

  resources :users, except: [:destroy, :create] do
    # resources :avatars
    member do
      post :follow
      post :unfollow
      get :followers
      get :followees
      get :news
      post :likes
      post :unlikes
      get :search
    end
  end

  get 'mailbox' => 'mailbox#index', as: :mailbox_index
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  # resources :mailbox, only: [:inbox, :sent, :trash]

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get 'search', to: 'search#search'
  # resources :profiles do
  #   member do
  #     post :follow
  #     post :unfollow
  #   end
  # end

  # resources :dialogs do
  #   resources :messages
  # end

  # resources :conversations, only: [:index, :show, :destroy] do
  #   collection do
  #     delete :empty_trash
  #   end
  # member do
  #   post :reply
  #   post :mark_as_read
  # end
  # end
  # resources :messages, only: [:new, :create] do
  #   member do
  #     post :restore
  #   end
  # end
  # post 'users#followers'
 #root 'posts#profile'
  # root 'user', to: 'users#show'

  #root 'profiles'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'users/profile', as: 'user_root'
  # get 'users/show', as: 'users'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  paginates_per 3

  acts_as_likeable
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
    #has_many :likes, #dependent: :destroy

    acts_as_likeable
    # acts_as_followable
end

app/models/user.rb
require 'elasticsearch/model'
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mapping do
    indexes :email, type: 'text'
    indexes :first_name, type: 'string', :index_analyzer => 'simple', :search_analyzer => 'simple'
    indexes :second_name, type: 'string', :index_analyzer => 'simple', :search_analyzer => 'simple'
  end
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable


  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  has_many :comments
  #validates :name, presence: true


  acts_as_followable
  acts_as_follower
  acts_as_liker

  acts_as_messageable



  def mailboxer_name
    self.first_name
  end

  def mailboxer_email(object)
    self.email
  end

  # def full_name
  #   "#{first_name} #{second_name}"
  # end

  def as_indexed_json (options={})
    self.as_json({
      only: [:id, :first_name, :second_name],
      include: [:posts],
      # methods: [:full_name]
     })
  end

  def self.search(query)
    __elasticsearch__.search(
        {
            query: {
                multi_match: {
                    query: query,
                    fields: ['first_name', 'second_name']
                }
            },
            highlight: {
              pre_tags: ['<em>'],
              post_tags: ['</em>'],
              fields: {
                  first_name: {},
                  second_name: {}
            }
        }
      }
    )
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :first_name, analyzer: 'english'
      indexes :second_name, analyzer: 'english'
    end
  end

  #attr_accessible :image, :image_cash, :remote_image
  #has_attached_file :avatar, :styles => { :thumb => "75x75>", :small => "150x150>" }
end
# User.import
# @user = User.search('fion').records

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def home
    if current_user
      redirect_to current_user
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :likes, :unlikes, :load_comments]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @user = current_user.posts
    #@comment = Comment.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save!
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    # @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def likes
    current_user.like!(@post)
    render :like_button
    # redirect_to :back, notice: "Liked this post successfully!"
  end

  def unlikes
    current_user.unlike!(@post)
    render :like_button
    # redirect_to :back, notice: "Unliked this post successfully!"
  end

  def load_comments
    @comments = Comment.order(created_at: :desc).where('id < ?', params[:comment_id]).limit(3)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post

      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :image, :comment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_header(text)
    content_for(:page_header) { text.to_s }
  end

  def flash_class(level)
    case level
      when 'notice' then "alert alert-dismissable alert-info"
      when 'success' then "alert alert-dismissable alert-success"
      when 'error', 'alert' then "alert alert-dismissable alert-danger"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    if resource.errors.full_messages.any?
      flash.now[:error] = resource.errors.full_messages.join(', ')
    end
    return ''
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  # def unread_messages_count
  #   # how to get the number of unread messages for the current user
  #   # using mailboxer
  #   mailbox.inbox(:unread => true).count(:id, :distinct => true)
  # end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name} #{user.second_name}</option>"
    end
    s.html_safe
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_comment.html.haml
.row.news-coment
  .col-sm-2
    %img= image_tag comment.user.avatar.url
  .col-sm-5
    .panel.panel-default
      .panel-heading
        %strong= link_to("#{comment.user.first_name} #{comment.user.second_name}", user_path(comment.user))
        %span.text-muted #{comment.created_at.strftime('%-d %B %Y, %H:%M:%S')}
      .panel-body
        = comment.text

app/views/posts/_comments.html.haml
%link{:href => "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", :rel => "stylesheet"}
-# так надо
.container
  .row.news
    .col-sm-12.news{id: "post-comments-#{post.id}"}
      %h2 Users Comments
      = link_to 'Load more', post_comments_path(post, page: 2), remote: true, class: 'load-more'
      .comments_block
        - post.comments.order(:created_at).last(3).each do |comment|
          = render 'posts/comment', comment: comment


    .news
      %h5 Add a comment:
      = form_for [post, post.comments.build], remote: true do |f|
        %p
          = f.text_area :text
        %p
          = f.submit

app/views/posts/_form.html.haml
%body.bg
  .container
    .row
      .main-login.main-center
        = form_for @post, html: { multipart: true } do |f|
          - if @post.errors.any?
            #error_explanation
              %h2
                = pluralize(@post.errors.count, "error")
                prohibited this post from being saved:
              %ul
                - @post.errors.full_messages.each do |message|
                  %li= message
          -#.field.text-center
          -#  = f.label :name
          -#  = f.text_field :name
          .field.text-center
            = f.label :description
            = f.text_area :description
          .field.text-center
            = f.label :image
            .post-new= f.file_field :image
          .actions.text-center{style: 'padding-top: 30px'}
            = f.submit 'Save'

app/views/posts/_like_button.html.haml
- if current_user.likes?(@post)
  = link_to unlikes_post_path(@post), method: :post, remote: true do
    %i.fa.fa-heart
- else
  = link_to likes_post_path(@post), method: :post, remote: true do
    %i.fa.fa-heart-o
= @post.likers(User).count

app/views/posts/edit.html.haml
%h1.text-center Editing post

= render 'form'

= link_to 'Show', @post
-#\|
-#= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1.text-center Listing posts

%table{align: 'center', cellpadding: '20px'}
  %thead
    %tr
      %th.text-center Image
      %th.text-center Name
      %th.text-center Description
      %th
      %th
      %th

  %tbody

    - @posts.each do |post|
      %tr
        %td= image_tag post.image.thumb
        %td= post.name
        %td= post.description
        %td= link_to 'Show', post
        -#%td= link_to 'Edit', edit_post_path(post)
        -#%td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }


%br
-#- if current_user = profile.user
-#= link_to 'New Post', new_post_path

app/views/posts/like_button.js.haml
$(".like_button.post-like-#{@post.id}").html("#{escape_javascript render(partial: 'posts/like_button', locals: { post: @post }) }")

app/views/posts/load_comments.js.haml
- @comments.each do |comment|
  $("#post-comments-#{@post.id}").append('#{j render 'posts/comment', post: @post, comment: comment}');
$('.load-more').href = "/load_comments?comment_id=" + "#{@comments.first.id}"

app/views/posts/new.html.haml
%h1.text-center New post

= render 'form'

-#= link_to 'Back', profile_path(current_user.profile.id)

app/views/posts/show.html.haml
%link{:href => "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", :rel => "stylesheet"}
-# так надо
.container
  .card.card-news{style: 'width: 70rem'}
    .news
      %p.text-center
        = image_tag @post.image
      .row
        .news{style: 'display: inline-block'}
          .img-img2= image_tag("#{@post.user.avatar.url}", class: 'img-img2')
          %a.account-name= link_to("#{@post.user.first_name} #{@post.user.second_name}", user_path(@post.user))
      %p
        %b Description:
        = @post.description
      - if current_user.id == @post.user.id
        %td= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'Edit', edit_post_path(@post)

      .like_button{class: "post-like-#{@post.id}"}
        - if current_user.likes?(@post)
          = link_to unlikes_post_path(@post), method: :post, remote: true do
            %i.fa.fa-heart
        - else
          = link_to likes_post_path(@post), method: :post, remote: true do
            %i.fa.fa-heart-o
        = @post.likers(User).count

      %p.timestamp #{@post.created_at.strftime('%-d %B %Y, %H:%M:%S')}

    #com{class: "com-#{@post.id}"}
      = render 'comments', post: @post
    -#.row
    -#  .col-sm-12.news
    -#    %h2 Users Comments
    -#    - @post.comments.each do |comment|
    -#      .row
    -#        .col-sm-2
    -#          %img= image_tag comment.user.avatar.url
    -#        .col-sm-5
    -#          .panel.panel-default
    -#            .panel-heading
    -#              %strong= link_to("#{comment.user.first_name} #{comment.user.second_name}", user_path(comment.user))
    -#              %span.text-muted #{comment.created_at.to_date}
    -#            .panel-body
    -#              = comment.text

    -#- @post.comments.each do |comment|
    -#  %p
    -#    %strong Commenter:
    -#    = comment.post.user.first_name
    -#    = comment.post.user.second_name
    -#  %p
    -#    %strong Comment:
    -#    = comment.text

    -#.news
    -#  %h5 Add a comment:
    -#  = form_for([@post, @post.comments.build]) do |f|
    -#    %p
    -#      = f.text_area :text
    -#    %p
    -#      = f.submit